name: teoria_gpt_app
description: אפליקציית מאמן אישי ללימוד תאוריה עם GPT
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.32.0
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.15.5
  provider: ^6.1.2
  http: ^0.13.6
  google_sign_in: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/theory_questions.json
